# Generated by Django 5.0.6 on 2024-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='number_of_years',
            field=models.IntegerField(default=3),
        ),
    ]
