# Generated by Django 5.0.6 on 2024-06-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncomplaintissue',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.academicyear'),
        ),
    ]
