# Generated by Django 5.0.6 on 2024-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_commoncomplaintissue_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncomplaintissue',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
